# Basic
title: Q1sj Blog
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="https://github.com/q1sj">@q1sj</a>

url: "http://q1sj.cn"

permalink: /:year/:month/:title/

# Format
markdown: kramdown
highlighter: rouge
kramdown:
    syntax_highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Q1sj blog

# Navigation buttons in the front page.
nav:
    - {title: Github, description: Github Projects, url: 'https://github.com/q1sj'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: q1sj
    # duoshuo: 
    
# Social
social:
#    weibo: q1sj
    github: q1sj
#    twitter: q1sj
#    gplus: 107108267983477358170
    mail: q1sj@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
